// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerAvatarType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Player {

  /// <summary>Holder for reflection information generated from PlayerAvatarType.proto</summary>
  public static partial class PlayerAvatarTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerAvatarType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerAvatarTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZQbGF5ZXJBdmF0YXJUeXBlLnByb3RvEhZQT0dPUHJvdG9zLkRhdGEuUGxh",
            "eWVyKkQKEFBsYXllckF2YXRhclR5cGUSFgoSUExBWUVSX0FWQVRBUl9NQUxF",
            "EAASGAoUUExBWUVSX0FWQVRBUl9GRU1BTEUQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Data.Player.PlayerAvatarType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PlayerAvatarType {
    [pbr::OriginalName("PLAYER_AVATAR_MALE")] PlayerAvatarMale = 0,
    [pbr::OriginalName("PLAYER_AVATAR_FEMALE")] PlayerAvatarFemale = 1,
  }

  #endregion

}

#endregion Designer generated code
