// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EncounterType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from EncounterType.proto</summary>
  public static partial class EncounterTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for EncounterType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EncounterTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNFbmNvdW50ZXJUeXBlLnByb3RvEhBQT0dPUHJvdG9zLkVudW1zKjcKDUVu",
            "Y291bnRlclR5cGUSDwoLU1BBV05fUE9JTlQQABILCgdJTkNFTlNFEAESCAoE",
            "RElTSxACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.EncounterType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EncounterType {
    [pbr::OriginalName("SPAWN_POINT")] SpawnPoint = 0,
    [pbr::OriginalName("INCENSE")] Incense = 1,
    [pbr::OriginalName("DISK")] Disk = 2,
  }

  #endregion

}

#endregion Designer generated code
