// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Filter.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from Filter.proto</summary>
  public static partial class FilterReflection {

    #region Descriptor
    /// <summary>File descriptor for Filter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FilterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxGaWx0ZXIucHJvdG8SEFBPR09Qcm90b3MuRW51bXMqagoGRmlsdGVyEhAK",
            "DFVOU0VUX0ZJTFRFUhAAEgcKA0FMTBABEgsKB0RFRkFVTFQQAhIJCgVPV05F",
            "RBADEgwKCEZFQVRVUkVEEAQSDwoLUFVSQ0hBU0FCTEUQBRIOCgpVTkxPQ0tB",
            "QkxFEAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Filter), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Filter {
    [pbr::OriginalName("UNSET_FILTER")] UnsetFilter = 0,
    [pbr::OriginalName("ALL")] All = 1,
    [pbr::OriginalName("DEFAULT")] Default = 2,
    [pbr::OriginalName("OWNED")] Owned = 3,
    [pbr::OriginalName("FEATURED")] Featured = 4,
    [pbr::OriginalName("PURCHASABLE")] Purchasable = 5,
    [pbr::OriginalName("UNLOCKABLE")] Unlockable = 6,
  }

  #endregion

}

#endregion Designer generated code
