// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PokemonRarity.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from PokemonRarity.proto</summary>
  public static partial class PokemonRarityReflection {

    #region Descriptor
    /// <summary>File descriptor for PokemonRarity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PokemonRarityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQb2tlbW9uUmFyaXR5LnByb3RvEhBQT0dPUHJvdG9zLkVudW1zKmMKDVBv",
            "a2Vtb25SYXJpdHkSGQoVUE9LRU1PTl9SQVJJVFlfTk9STUFMEAASHAoYUE9L",
            "RU1PTl9SQVJJVFlfTEVHRU5EQVJZEAESGQoVUE9LRU1PTl9SQVJJVFlfTVlU",
            "SElDEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.PokemonRarity), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PokemonRarity {
    [pbr::OriginalName("POKEMON_RARITY_NORMAL")] Normal = 0,
    [pbr::OriginalName("POKEMON_RARITY_LEGENDARY")] Legendary = 1,
    [pbr::OriginalName("POKEMON_RARITY_MYTHIC")] Mythic = 2,
  }

  #endregion

}

#endregion Designer generated code
