// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuestType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from QuestType.proto</summary>
  public static partial class QuestTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for QuestType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuestTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9RdWVzdFR5cGUucHJvdG8SEFBPR09Qcm90b3MuRW51bXMqagoJUXVlc3RU",
            "eXBlEhYKElFVRVNUX1VOS05PV05fVFlQRRAAEiAKHFFVRVNUX0ZJUlNUX0NB",
            "VENIX09GX1RIRV9EQVkQARIjCh9RVUVTVF9GSVJTVF9QT0tFU1RPUF9PRl9U",
            "SEVfREFZEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.QuestType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum QuestType {
    [pbr::OriginalName("QUEST_UNKNOWN_TYPE")] QuestUnknownType = 0,
    [pbr::OriginalName("QUEST_FIRST_CATCH_OF_THE_DAY")] QuestFirstCatchOfTheDay = 1,
    [pbr::OriginalName("QUEST_FIRST_POKESTOP_OF_THE_DAY")] QuestFirstPokestopOfTheDay = 2,
  }

  #endregion

}

#endregion Designer generated code
