// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slot.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from Slot.proto</summary>
  public static partial class SlotReflection {

    #region Descriptor
    /// <summary>File descriptor for Slot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SlotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpTbG90LnByb3RvEhBQT0dPUHJvdG9zLkVudW1zKnkKBFNsb3QSDgoKVU5T",
            "RVRfU0xPVBAAEggKBEhBSVIQARIJCgVTSElSVBACEgkKBVBBTlRTEAMSBwoD",
            "SEFUEAQSCQoFU0hPRVMQBRIICgRFWUVTEAYSDAoIQkFDS1BBQ0sQBxIKCgZH",
            "TE9WRVMQCBIJCgVTT0NLUxAJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Slot), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Slot {
    [pbr::OriginalName("UNSET_SLOT")] UnsetSlot = 0,
    [pbr::OriginalName("HAIR")] Hair = 1,
    [pbr::OriginalName("SHIRT")] Shirt = 2,
    [pbr::OriginalName("PANTS")] Pants = 3,
    [pbr::OriginalName("HAT")] Hat = 4,
    [pbr::OriginalName("SHOES")] Shoes = 5,
    [pbr::OriginalName("EYES")] Eyes = 6,
    [pbr::OriginalName("BACKPACK")] Backpack = 7,
    [pbr::OriginalName("GLOVES")] Gloves = 8,
    [pbr::OriginalName("SOCKS")] Socks = 9,
  }

  #endregion

}

#endregion Designer generated code
