// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuyItemPokeCoinsResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Platform.Responses {

  /// <summary>Holder for reflection information generated from BuyItemPokeCoinsResponse.proto</summary>
  public static partial class BuyItemPokeCoinsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for BuyItemPokeCoinsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuyItemPokeCoinsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5CdXlJdGVtUG9rZUNvaW5zUmVzcG9uc2UucHJvdG8SKFBPR09Qcm90b3Mu",
            "TmV0d29ya2luZy5QbGF0Zm9ybS5SZXNwb25zZXMiswEKGEJ1eUl0ZW1Qb2tl",
            "Q29pbnNSZXNwb25zZRJZCgZyZXN1bHQYASABKA4ySS5QT0dPUHJvdG9zLk5l",
            "dHdvcmtpbmcuUGxhdGZvcm0uUmVzcG9uc2VzLkJ1eUl0ZW1Qb2tlQ29pbnNS",
            "ZXNwb25zZS5TdGF0dXMiPAoGU3RhdHVzEgsKB1VOS05PV04QABILCgdTVUND",
            "RVNTEAESGAoUTk9UX0VOT1VHSF9QT0tFQ09JTlMQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse), global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Parser, new[]{ "Result" }, null, new[]{ typeof(global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BuyItemPokeCoinsResponse : pb::IMessage<BuyItemPokeCoinsResponse> {
    private static readonly pb::MessageParser<BuyItemPokeCoinsResponse> _parser = new pb::MessageParser<BuyItemPokeCoinsResponse>(() => new BuyItemPokeCoinsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BuyItemPokeCoinsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyItemPokeCoinsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyItemPokeCoinsResponse(BuyItemPokeCoinsResponse other) : this() {
      result_ = other.result_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyItemPokeCoinsResponse Clone() {
      return new BuyItemPokeCoinsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Types.Status result_ = 0;
    /// <summary>
    ///  result
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Types.Status Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BuyItemPokeCoinsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BuyItemPokeCoinsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BuyItemPokeCoinsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Types.Status) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BuyItemPokeCoinsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      ///  THESE ARE SOMEWHAT SPECULATED, should be a NOT ENOUGH ROOM status too for bag being full somewhere.
      /// </summary>
      public enum Status {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("NOT_ENOUGH_POKECOINS")] NotEnoughPokecoins = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
