// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendEncryptedSignatureResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Platform.Responses {

  /// <summary>Holder for reflection information generated from SendEncryptedSignatureResponse.proto</summary>
  public static partial class SendEncryptedSignatureResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for SendEncryptedSignatureResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SendEncryptedSignatureResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRTZW5kRW5jcnlwdGVkU2lnbmF0dXJlUmVzcG9uc2UucHJvdG8SKFBPR09Q",
            "cm90b3MuTmV0d29ya2luZy5QbGF0Zm9ybS5SZXNwb25zZXMiMgoeU2VuZEVu",
            "Y3J5cHRlZFNpZ25hdHVyZVJlc3BvbnNlEhAKCHJlY2VpdmVkGAEgASgIYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse), global::POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse.Parser, new[]{ "Received" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SendEncryptedSignatureResponse : pb::IMessage<SendEncryptedSignatureResponse> {
    private static readonly pb::MessageParser<SendEncryptedSignatureResponse> _parser = new pb::MessageParser<SendEncryptedSignatureResponse>(() => new SendEncryptedSignatureResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SendEncryptedSignatureResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendEncryptedSignatureResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendEncryptedSignatureResponse(SendEncryptedSignatureResponse other) : this() {
      received_ = other.received_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendEncryptedSignatureResponse Clone() {
      return new SendEncryptedSignatureResponse(this);
    }

    /// <summary>Field number for the "received" field.</summary>
    public const int ReceivedFieldNumber = 1;
    private bool received_;
    /// <summary>
    ///  speculated, could be an enum
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Received {
      get { return received_; }
      set {
        received_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SendEncryptedSignatureResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SendEncryptedSignatureResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Received != other.Received) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Received != false) hash ^= Received.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Received != false) {
        output.WriteRawTag(8);
        output.WriteBool(Received);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Received != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SendEncryptedSignatureResponse other) {
      if (other == null) {
        return;
      }
      if (other.Received != false) {
        Received = other.Received;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Received = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
