// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory.Item {

  /// <summary>Holder for reflection information generated from ItemType.proto</summary>
  public static partial class ItemTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5JdGVtVHlwZS5wcm90bxIZUE9HT1Byb3Rvcy5JbnZlbnRvcnkuSXRlbSqy",
            "AgoISXRlbVR5cGUSEgoOSVRFTV9UWVBFX05PTkUQABIWChJJVEVNX1RZUEVf",
            "UE9LRUJBTEwQARIUChBJVEVNX1RZUEVfUE9USU9OEAISFAoQSVRFTV9UWVBF",
            "X1JFVklWRRADEhEKDUlURU1fVFlQRV9NQVAQBBIUChBJVEVNX1RZUEVfQkFU",
            "VExFEAUSEgoOSVRFTV9UWVBFX0ZPT0QQBhIUChBJVEVNX1RZUEVfQ0FNRVJB",
            "EAcSEgoOSVRFTV9UWVBFX0RJU0sQCBIXChNJVEVNX1RZUEVfSU5DVUJBVE9S",
            "EAkSFQoRSVRFTV9UWVBFX0lOQ0VOU0UQChIWChJJVEVNX1RZUEVfWFBfQk9P",
            "U1QQCxIfChtJVEVNX1RZUEVfSU5WRU5UT1JZX1VQR1JBREUQDGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Inventory.Item.ItemType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemType {
    [pbr::OriginalName("ITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ITEM_TYPE_POKEBALL")] Pokeball = 1,
    [pbr::OriginalName("ITEM_TYPE_POTION")] Potion = 2,
    [pbr::OriginalName("ITEM_TYPE_REVIVE")] Revive = 3,
    [pbr::OriginalName("ITEM_TYPE_MAP")] Map = 4,
    [pbr::OriginalName("ITEM_TYPE_BATTLE")] Battle = 5,
    [pbr::OriginalName("ITEM_TYPE_FOOD")] Food = 6,
    [pbr::OriginalName("ITEM_TYPE_CAMERA")] Camera = 7,
    [pbr::OriginalName("ITEM_TYPE_DISK")] Disk = 8,
    [pbr::OriginalName("ITEM_TYPE_INCUBATOR")] Incubator = 9,
    [pbr::OriginalName("ITEM_TYPE_INCENSE")] Incense = 10,
    [pbr::OriginalName("ITEM_TYPE_XP_BOOST")] XpBoost = 11,
    [pbr::OriginalName("ITEM_TYPE_INVENTORY_UPGRADE")] InventoryUpgrade = 12,
  }

  #endregion

}

#endregion Designer generated code
