// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryItem.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from InventoryItem.proto</summary>
  public static partial class InventoryItemReflection {

    #region Descriptor
    /// <summary>File descriptor for InventoryItem.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InventoryItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNJbnZlbnRvcnlJdGVtLnByb3RvEhRQT0dPUHJvdG9zLkludmVudG9yeRos",
            "UE9HT1Byb3Rvcy9JbnZlbnRvcnkvSW52ZW50b3J5SXRlbURhdGEucHJvdG8i",
            "3gEKDUludmVudG9yeUl0ZW0SHQoVbW9kaWZpZWRfdGltZXN0YW1wX21zGAEg",
            "ASgDEkUKDGRlbGV0ZWRfaXRlbRgCIAEoCzIvLlBPR09Qcm90b3MuSW52ZW50",
            "b3J5LkludmVudG9yeUl0ZW0uRGVsZXRlZEl0ZW0SRAoTaW52ZW50b3J5X2l0",
            "ZW1fZGF0YRgDIAEoCzInLlBPR09Qcm90b3MuSW52ZW50b3J5LkludmVudG9y",
            "eUl0ZW1EYXRhGiEKC0RlbGV0ZWRJdGVtEhIKCnBva2Vtb25faWQYASABKAZi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.InventoryItemDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Inventory.InventoryItem), global::POGOProtos.Inventory.InventoryItem.Parser, new[]{ "ModifiedTimestampMs", "DeletedItem", "InventoryItemData" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem), global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem.Parser, new[]{ "PokemonId" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InventoryItem : pb::IMessage<InventoryItem> {
    private static readonly pb::MessageParser<InventoryItem> _parser = new pb::MessageParser<InventoryItem>(() => new InventoryItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InventoryItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Inventory.InventoryItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InventoryItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InventoryItem(InventoryItem other) : this() {
      modifiedTimestampMs_ = other.modifiedTimestampMs_;
      DeletedItem = other.deletedItem_ != null ? other.DeletedItem.Clone() : null;
      InventoryItemData = other.inventoryItemData_ != null ? other.InventoryItemData.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InventoryItem Clone() {
      return new InventoryItem(this);
    }

    /// <summary>Field number for the "modified_timestamp_ms" field.</summary>
    public const int ModifiedTimestampMsFieldNumber = 1;
    private long modifiedTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ModifiedTimestampMs {
      get { return modifiedTimestampMs_; }
      set {
        modifiedTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "deleted_item" field.</summary>
    public const int DeletedItemFieldNumber = 2;
    private global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem deletedItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem DeletedItem {
      get { return deletedItem_; }
      set {
        deletedItem_ = value;
      }
    }

    /// <summary>Field number for the "inventory_item_data" field.</summary>
    public const int InventoryItemDataFieldNumber = 3;
    private global::POGOProtos.Inventory.InventoryItemData inventoryItemData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.InventoryItemData InventoryItemData {
      get { return inventoryItemData_; }
      set {
        inventoryItemData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InventoryItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InventoryItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ModifiedTimestampMs != other.ModifiedTimestampMs) return false;
      if (!object.Equals(DeletedItem, other.DeletedItem)) return false;
      if (!object.Equals(InventoryItemData, other.InventoryItemData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ModifiedTimestampMs != 0L) hash ^= ModifiedTimestampMs.GetHashCode();
      if (deletedItem_ != null) hash ^= DeletedItem.GetHashCode();
      if (inventoryItemData_ != null) hash ^= InventoryItemData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ModifiedTimestampMs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ModifiedTimestampMs);
      }
      if (deletedItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeletedItem);
      }
      if (inventoryItemData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InventoryItemData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ModifiedTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ModifiedTimestampMs);
      }
      if (deletedItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeletedItem);
      }
      if (inventoryItemData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InventoryItemData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InventoryItem other) {
      if (other == null) {
        return;
      }
      if (other.ModifiedTimestampMs != 0L) {
        ModifiedTimestampMs = other.ModifiedTimestampMs;
      }
      if (other.deletedItem_ != null) {
        if (deletedItem_ == null) {
          deletedItem_ = new global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem();
        }
        DeletedItem.MergeFrom(other.DeletedItem);
      }
      if (other.inventoryItemData_ != null) {
        if (inventoryItemData_ == null) {
          inventoryItemData_ = new global::POGOProtos.Inventory.InventoryItemData();
        }
        InventoryItemData.MergeFrom(other.InventoryItemData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ModifiedTimestampMs = input.ReadInt64();
            break;
          }
          case 18: {
            if (deletedItem_ == null) {
              deletedItem_ = new global::POGOProtos.Inventory.InventoryItem.Types.DeletedItem();
            }
            input.ReadMessage(deletedItem_);
            break;
          }
          case 26: {
            if (inventoryItemData_ == null) {
              inventoryItemData_ = new global::POGOProtos.Inventory.InventoryItemData();
            }
            input.ReadMessage(inventoryItemData_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the InventoryItem message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class DeletedItem : pb::IMessage<DeletedItem> {
        private static readonly pb::MessageParser<DeletedItem> _parser = new pb::MessageParser<DeletedItem>(() => new DeletedItem());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<DeletedItem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::POGOProtos.Inventory.InventoryItem.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeletedItem() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeletedItem(DeletedItem other) : this() {
          pokemonId_ = other.pokemonId_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeletedItem Clone() {
          return new DeletedItem(this);
        }

        /// <summary>Field number for the "pokemon_id" field.</summary>
        public const int PokemonIdFieldNumber = 1;
        private ulong pokemonId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong PokemonId {
          get { return pokemonId_; }
          set {
            pokemonId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as DeletedItem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(DeletedItem other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (PokemonId != other.PokemonId) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (PokemonId != 0UL) hash ^= PokemonId.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (PokemonId != 0UL) {
            output.WriteRawTag(9);
            output.WriteFixed64(PokemonId);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (PokemonId != 0UL) {
            size += 1 + 8;
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(DeletedItem other) {
          if (other == null) {
            return;
          }
          if (other.PokemonId != 0UL) {
            PokemonId = other.PokemonId;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 9: {
                PokemonId = input.ReadFixed64();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
