// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFortModifierResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from AddFortModifierResponse.proto</summary>
  public static partial class AddFortModifierResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for AddFortModifierResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddFortModifierResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1BZGRGb3J0TW9kaWZpZXJSZXNwb25zZS5wcm90bxIfUE9HT1Byb3Rvcy5O",
            "ZXR3b3JraW5nLlJlc3BvbnNlcxo5UE9HT1Byb3Rvcy9OZXR3b3JraW5nL1Jl",
            "c3BvbnNlcy9Gb3J0RGV0YWlsc1Jlc3BvbnNlLnByb3RvIqsCChdBZGRGb3J0",
            "TW9kaWZpZXJSZXNwb25zZRJPCgZyZXN1bHQYASABKA4yPy5QT0dPUHJvdG9z",
            "Lk5ldHdvcmtpbmcuUmVzcG9uc2VzLkFkZEZvcnRNb2RpZmllclJlc3BvbnNl",
            "LlJlc3VsdBJKCgxmb3J0X2RldGFpbHMYAiABKAsyNC5QT0dPUHJvdG9zLk5l",
            "dHdvcmtpbmcuUmVzcG9uc2VzLkZvcnREZXRhaWxzUmVzcG9uc2UicwoGUmVz",
            "dWx0EhEKDU5PX1JFU1VMVF9TRVQQABILCgdTVUNDRVNTEAESHQoZRk9SVF9B",
            "TFJFQURZX0hBU19NT0RJRklFUhACEhAKDFRPT19GQVJfQVdBWRADEhgKFE5P",
            "X0lURU1fSU5fSU5WRU5UT1JZEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Networking.Responses.FortDetailsResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.AddFortModifierResponse), global::POGOProtos.Networking.Responses.AddFortModifierResponse.Parser, new[]{ "Result", "FortDetails" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.AddFortModifierResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AddFortModifierResponse : pb::IMessage<AddFortModifierResponse> {
    private static readonly pb::MessageParser<AddFortModifierResponse> _parser = new pb::MessageParser<AddFortModifierResponse>(() => new AddFortModifierResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddFortModifierResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.AddFortModifierResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddFortModifierResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddFortModifierResponse(AddFortModifierResponse other) : this() {
      result_ = other.result_;
      FortDetails = other.fortDetails_ != null ? other.FortDetails.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddFortModifierResponse Clone() {
      return new AddFortModifierResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.AddFortModifierResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.AddFortModifierResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "fort_details" field.</summary>
    public const int FortDetailsFieldNumber = 2;
    private global::POGOProtos.Networking.Responses.FortDetailsResponse fortDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.FortDetailsResponse FortDetails {
      get { return fortDetails_; }
      set {
        fortDetails_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddFortModifierResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddFortModifierResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(FortDetails, other.FortDetails)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (fortDetails_ != null) hash ^= FortDetails.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (fortDetails_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FortDetails);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (fortDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FortDetails);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddFortModifierResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.fortDetails_ != null) {
        if (fortDetails_ == null) {
          fortDetails_ = new global::POGOProtos.Networking.Responses.FortDetailsResponse();
        }
        FortDetails.MergeFrom(other.FortDetails);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.AddFortModifierResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (fortDetails_ == null) {
              fortDetails_ = new global::POGOProtos.Networking.Responses.FortDetailsResponse();
            }
            input.ReadMessage(fortDetails_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AddFortModifierResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("NO_RESULT_SET")] NoResultSet = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("FORT_ALREADY_HAS_MODIFIER")] FortAlreadyHasModifier = 2,
        [pbr::OriginalName("TOO_FAR_AWAY")] TooFarAway = 3,
        [pbr::OriginalName("NO_ITEM_IN_INVENTORY")] NoItemInInventory = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
