// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FortDeployPokemonResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from FortDeployPokemonResponse.proto</summary>
  public static partial class FortDeployPokemonResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for FortDeployPokemonResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortDeployPokemonResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Gb3J0RGVwbG95UG9rZW1vblJlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9z",
            "Lk5ldHdvcmtpbmcuUmVzcG9uc2VzGiFQT0dPUHJvdG9zL0RhdGEvUG9rZW1v",
            "bkRhdGEucHJvdG8aIlBPR09Qcm90b3MvRGF0YS9HeW0vR3ltU3RhdGUucHJv",
            "dG8aOVBPR09Qcm90b3MvTmV0d29ya2luZy9SZXNwb25zZXMvRm9ydERldGFp",
            "bHNSZXNwb25zZS5wcm90byKFBQoZRm9ydERlcGxveVBva2Vtb25SZXNwb25z",
            "ZRJRCgZyZXN1bHQYASABKA4yQS5QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVz",
            "cG9uc2VzLkZvcnREZXBsb3lQb2tlbW9uUmVzcG9uc2UuUmVzdWx0EkoKDGZv",
            "cnRfZGV0YWlscxgCIAEoCzI0LlBPR09Qcm90b3MuTmV0d29ya2luZy5SZXNw",
            "b25zZXMuRm9ydERldGFpbHNSZXNwb25zZRIyCgxwb2tlbW9uX2RhdGEYAyAB",
            "KAsyHC5QT0dPUHJvdG9zLkRhdGEuUG9rZW1vbkRhdGESMAoJZ3ltX3N0YXRl",
            "GAQgASgLMh0uUE9HT1Byb3Rvcy5EYXRhLkd5bS5HeW1TdGF0ZSLiAgoGUmVz",
            "dWx0EhEKDU5PX1JFU1VMVF9TRVQQABILCgdTVUNDRVNTEAESJQohRVJST1Jf",
            "QUxSRUFEWV9IQVNfUE9LRU1PTl9PTl9GT1JUEAISIQodRVJST1JfT1BQT1NJ",
            "TkdfVEVBTV9PV05TX0ZPUlQQAxIWChJFUlJPUl9GT1JUX0lTX0ZVTEwQBBIW",
            "ChJFUlJPUl9OT1RfSU5fUkFOR0UQBRIcChhFUlJPUl9QTEFZRVJfSEFTX05P",
            "X1RFQU0QBhIdChlFUlJPUl9QT0tFTU9OX05PVF9GVUxMX0hQEAcSJAogRVJS",
            "T1JfUExBWUVSX0JFTE9XX01JTklNVU1fTEVWRUwQCBIaChZFUlJPUl9QT0tF",
            "TU9OX0lTX0JVRERZEAkSHQoZRVJST1JfRk9SVF9ERVBMT1lfTE9DS09VVBAK",
            "EiAKHEVSUk9SX1BMQVlFUl9IQVNfTk9fTklDS05BTUUQC2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.PokemonDataReflection.Descriptor, global::POGOProtos.Data.Gym.GymStateReflection.Descriptor, global::POGOProtos.Networking.Responses.FortDetailsResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.FortDeployPokemonResponse), global::POGOProtos.Networking.Responses.FortDeployPokemonResponse.Parser, new[]{ "Result", "FortDetails", "PokemonData", "GymState" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.FortDeployPokemonResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FortDeployPokemonResponse : pb::IMessage<FortDeployPokemonResponse> {
    private static readonly pb::MessageParser<FortDeployPokemonResponse> _parser = new pb::MessageParser<FortDeployPokemonResponse>(() => new FortDeployPokemonResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FortDeployPokemonResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.FortDeployPokemonResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FortDeployPokemonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FortDeployPokemonResponse(FortDeployPokemonResponse other) : this() {
      result_ = other.result_;
      FortDetails = other.fortDetails_ != null ? other.FortDetails.Clone() : null;
      PokemonData = other.pokemonData_ != null ? other.PokemonData.Clone() : null;
      GymState = other.gymState_ != null ? other.GymState.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FortDeployPokemonResponse Clone() {
      return new FortDeployPokemonResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.FortDeployPokemonResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.FortDeployPokemonResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "fort_details" field.</summary>
    public const int FortDetailsFieldNumber = 2;
    private global::POGOProtos.Networking.Responses.FortDetailsResponse fortDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.FortDetailsResponse FortDetails {
      get { return fortDetails_; }
      set {
        fortDetails_ = value;
      }
    }

    /// <summary>Field number for the "pokemon_data" field.</summary>
    public const int PokemonDataFieldNumber = 3;
    private global::POGOProtos.Data.PokemonData pokemonData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonData PokemonData {
      get { return pokemonData_; }
      set {
        pokemonData_ = value;
      }
    }

    /// <summary>Field number for the "gym_state" field.</summary>
    public const int GymStateFieldNumber = 4;
    private global::POGOProtos.Data.Gym.GymState gymState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Gym.GymState GymState {
      get { return gymState_; }
      set {
        gymState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FortDeployPokemonResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FortDeployPokemonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(FortDetails, other.FortDetails)) return false;
      if (!object.Equals(PokemonData, other.PokemonData)) return false;
      if (!object.Equals(GymState, other.GymState)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (fortDetails_ != null) hash ^= FortDetails.GetHashCode();
      if (pokemonData_ != null) hash ^= PokemonData.GetHashCode();
      if (gymState_ != null) hash ^= GymState.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (fortDetails_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FortDetails);
      }
      if (pokemonData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PokemonData);
      }
      if (gymState_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GymState);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (fortDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FortDetails);
      }
      if (pokemonData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PokemonData);
      }
      if (gymState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GymState);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FortDeployPokemonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.fortDetails_ != null) {
        if (fortDetails_ == null) {
          fortDetails_ = new global::POGOProtos.Networking.Responses.FortDetailsResponse();
        }
        FortDetails.MergeFrom(other.FortDetails);
      }
      if (other.pokemonData_ != null) {
        if (pokemonData_ == null) {
          pokemonData_ = new global::POGOProtos.Data.PokemonData();
        }
        PokemonData.MergeFrom(other.PokemonData);
      }
      if (other.gymState_ != null) {
        if (gymState_ == null) {
          gymState_ = new global::POGOProtos.Data.Gym.GymState();
        }
        GymState.MergeFrom(other.GymState);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.FortDeployPokemonResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (fortDetails_ == null) {
              fortDetails_ = new global::POGOProtos.Networking.Responses.FortDetailsResponse();
            }
            input.ReadMessage(fortDetails_);
            break;
          }
          case 26: {
            if (pokemonData_ == null) {
              pokemonData_ = new global::POGOProtos.Data.PokemonData();
            }
            input.ReadMessage(pokemonData_);
            break;
          }
          case 34: {
            if (gymState_ == null) {
              gymState_ = new global::POGOProtos.Data.Gym.GymState();
            }
            input.ReadMessage(gymState_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FortDeployPokemonResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("NO_RESULT_SET")] NoResultSet = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_ALREADY_HAS_POKEMON_ON_FORT")] ErrorAlreadyHasPokemonOnFort = 2,
        [pbr::OriginalName("ERROR_OPPOSING_TEAM_OWNS_FORT")] ErrorOpposingTeamOwnsFort = 3,
        [pbr::OriginalName("ERROR_FORT_IS_FULL")] ErrorFortIsFull = 4,
        [pbr::OriginalName("ERROR_NOT_IN_RANGE")] ErrorNotInRange = 5,
        [pbr::OriginalName("ERROR_PLAYER_HAS_NO_TEAM")] ErrorPlayerHasNoTeam = 6,
        [pbr::OriginalName("ERROR_POKEMON_NOT_FULL_HP")] ErrorPokemonNotFullHp = 7,
        [pbr::OriginalName("ERROR_PLAYER_BELOW_MINIMUM_LEVEL")] ErrorPlayerBelowMinimumLevel = 8,
        [pbr::OriginalName("ERROR_POKEMON_IS_BUDDY")] ErrorPokemonIsBuddy = 9,
        [pbr::OriginalName("ERROR_FORT_DEPLOY_LOCKOUT")] ErrorFortDeployLockout = 10,
        [pbr::OriginalName("ERROR_PLAYER_HAS_NO_NICKNAME")] ErrorPlayerHasNoNickname = 11,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
