// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetMapObjectsResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from GetMapObjectsResponse.proto</summary>
  public static partial class GetMapObjectsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for GetMapObjectsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetMapObjectsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtHZXRNYXBPYmplY3RzUmVzcG9uc2UucHJvdG8SH1BPR09Qcm90b3MuTmV0",
            "d29ya2luZy5SZXNwb25zZXMaHFBPR09Qcm90b3MvTWFwL01hcENlbGwucHJv",
            "dG8aJVBPR09Qcm90b3MvTWFwL01hcE9iamVjdHNTdGF0dXMucHJvdG8i9wEK",
            "FUdldE1hcE9iamVjdHNSZXNwb25zZRIqCgltYXBfY2VsbHMYASADKAsyFy5Q",
            "T0dPUHJvdG9zLk1hcC5NYXBDZWxsEjAKBnN0YXR1cxgCIAEoDjIgLlBPR09Q",
            "cm90b3MuTWFwLk1hcE9iamVjdHNTdGF0dXMSVQoLdGltZV9vZl9kYXkYAyAB",
            "KA4yQC5QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLkdldE1hcE9i",
            "amVjdHNSZXNwb25zZS5UaW1lT2ZEYXkiKQoJVGltZU9mRGF5EggKBE5PTkUQ",
            "ABIHCgNEQVkQARIJCgVOSUdIVBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Map.MapCellReflection.Descriptor, global::POGOProtos.Map.MapObjectsStatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.GetMapObjectsResponse), global::POGOProtos.Networking.Responses.GetMapObjectsResponse.Parser, new[]{ "MapCells", "Status", "TimeOfDay" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.GetMapObjectsResponse.Types.TimeOfDay) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetMapObjectsResponse : pb::IMessage<GetMapObjectsResponse> {
    private static readonly pb::MessageParser<GetMapObjectsResponse> _parser = new pb::MessageParser<GetMapObjectsResponse>(() => new GetMapObjectsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetMapObjectsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.GetMapObjectsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetMapObjectsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetMapObjectsResponse(GetMapObjectsResponse other) : this() {
      mapCells_ = other.mapCells_.Clone();
      status_ = other.status_;
      timeOfDay_ = other.timeOfDay_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetMapObjectsResponse Clone() {
      return new GetMapObjectsResponse(this);
    }

    /// <summary>Field number for the "map_cells" field.</summary>
    public const int MapCellsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::POGOProtos.Map.MapCell> _repeated_mapCells_codec
        = pb::FieldCodec.ForMessage(10, global::POGOProtos.Map.MapCell.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Map.MapCell> mapCells_ = new pbc::RepeatedField<global::POGOProtos.Map.MapCell>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Map.MapCell> MapCells {
      get { return mapCells_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::POGOProtos.Map.MapObjectsStatus status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Map.MapObjectsStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "time_of_day" field.</summary>
    public const int TimeOfDayFieldNumber = 3;
    private global::POGOProtos.Networking.Responses.GetMapObjectsResponse.Types.TimeOfDay timeOfDay_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.GetMapObjectsResponse.Types.TimeOfDay TimeOfDay {
      get { return timeOfDay_; }
      set {
        timeOfDay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetMapObjectsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetMapObjectsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mapCells_.Equals(other.mapCells_)) return false;
      if (Status != other.Status) return false;
      if (TimeOfDay != other.TimeOfDay) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mapCells_.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (TimeOfDay != 0) hash ^= TimeOfDay.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mapCells_.WriteTo(output, _repeated_mapCells_codec);
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (TimeOfDay != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TimeOfDay);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mapCells_.CalculateSize(_repeated_mapCells_codec);
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (TimeOfDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TimeOfDay);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetMapObjectsResponse other) {
      if (other == null) {
        return;
      }
      mapCells_.Add(other.mapCells_);
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.TimeOfDay != 0) {
        TimeOfDay = other.TimeOfDay;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mapCells_.AddEntriesFrom(input, _repeated_mapCells_codec);
            break;
          }
          case 16: {
            status_ = (global::POGOProtos.Map.MapObjectsStatus) input.ReadEnum();
            break;
          }
          case 24: {
            timeOfDay_ = (global::POGOProtos.Networking.Responses.GetMapObjectsResponse.Types.TimeOfDay) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GetMapObjectsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum TimeOfDay {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("DAY")] Day = 1,
        [pbr::OriginalName("NIGHT")] Night = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
