// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartGymBattleResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from StartGymBattleResponse.proto</summary>
  public static partial class StartGymBattleResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for StartGymBattleResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StartGymBattleResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxTdGFydEd5bUJhdHRsZVJlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9zLk5l",
            "dHdvcmtpbmcuUmVzcG9uc2VzGiZQT0dPUHJvdG9zL0RhdGEvQmF0dGxlL0Jh",
            "dHRsZUxvZy5wcm90bxouUE9HT1Byb3Rvcy9EYXRhL0JhdHRsZS9CYXR0bGVQ",
            "YXJ0aWNpcGFudC5wcm90byLsBQoWU3RhcnRHeW1CYXR0bGVSZXNwb25zZRJO",
            "CgZyZXN1bHQYASABKA4yPi5QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9u",
            "c2VzLlN0YXJ0R3ltQmF0dGxlUmVzcG9uc2UuUmVzdWx0EiEKGWJhdHRsZV9z",
            "dGFydF90aW1lc3RhbXBfbXMYAiABKAMSHwoXYmF0dGxlX2VuZF90aW1lc3Rh",
            "bXBfbXMYAyABKAMSEQoJYmF0dGxlX2lkGAQgASgJEjsKCGRlZmVuZGVyGAUg",
            "ASgLMikuUE9HT1Byb3Rvcy5EYXRhLkJhdHRsZS5CYXR0bGVQYXJ0aWNpcGFu",
            "dBI1CgpiYXR0bGVfbG9nGAYgASgLMiEuUE9HT1Byb3Rvcy5EYXRhLkJhdHRs",
            "ZS5CYXR0bGVMb2cSOwoIYXR0YWNrZXIYByABKAsyKS5QT0dPUHJvdG9zLkRh",
            "dGEuQmF0dGxlLkJhdHRsZVBhcnRpY2lwYW50IvkCCgZSZXN1bHQSCQoFVU5T",
            "RVQQABILCgdTVUNDRVNTEAESFwoTRVJST1JfR1lNX05PVF9GT1VORBACEhUK",
            "EUVSUk9SX0dZTV9ORVVUUkFMEAMSGAoURVJST1JfR1lNX1dST05HX1RFQU0Q",
            "BBITCg9FUlJPUl9HWU1fRU1QVFkQBRIaChZFUlJPUl9JTlZBTElEX0RFRkVO",
            "REVSEAYSKQolRVJST1JfVFJBSU5JTkdfSU5WQUxJRF9BVFRBQ0tFUl9DT1VO",
            "VBAHEh0KGUVSUk9SX0FMTF9QT0tFTU9OX0ZBSU5URUQQCBIaChZFUlJPUl9U",
            "T09fTUFOWV9CQVRUTEVTEAkSGgoWRVJST1JfVE9PX01BTllfUExBWUVSUxAK",
            "EhwKGEVSUk9SX0dZTV9CQVRUTEVfTE9DS09VVBALEiQKIEVSUk9SX1BMQVlF",
            "Ul9CRUxPV19NSU5JTVVNX0xFVkVMEAwSFgoSRVJST1JfTk9UX0lOX1JBTkdF",
            "EA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Battle.BattleLogReflection.Descriptor, global::POGOProtos.Data.Battle.BattleParticipantReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.StartGymBattleResponse), global::POGOProtos.Networking.Responses.StartGymBattleResponse.Parser, new[]{ "Result", "BattleStartTimestampMs", "BattleEndTimestampMs", "BattleId", "Defender", "BattleLog", "Attacker" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.StartGymBattleResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StartGymBattleResponse : pb::IMessage<StartGymBattleResponse> {
    private static readonly pb::MessageParser<StartGymBattleResponse> _parser = new pb::MessageParser<StartGymBattleResponse>(() => new StartGymBattleResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartGymBattleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.StartGymBattleResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGymBattleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGymBattleResponse(StartGymBattleResponse other) : this() {
      result_ = other.result_;
      battleStartTimestampMs_ = other.battleStartTimestampMs_;
      battleEndTimestampMs_ = other.battleEndTimestampMs_;
      battleId_ = other.battleId_;
      Defender = other.defender_ != null ? other.Defender.Clone() : null;
      BattleLog = other.battleLog_ != null ? other.BattleLog.Clone() : null;
      Attacker = other.attacker_ != null ? other.Attacker.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGymBattleResponse Clone() {
      return new StartGymBattleResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.StartGymBattleResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.StartGymBattleResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "battle_start_timestamp_ms" field.</summary>
    public const int BattleStartTimestampMsFieldNumber = 2;
    private long battleStartTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BattleStartTimestampMs {
      get { return battleStartTimestampMs_; }
      set {
        battleStartTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "battle_end_timestamp_ms" field.</summary>
    public const int BattleEndTimestampMsFieldNumber = 3;
    private long battleEndTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BattleEndTimestampMs {
      get { return battleEndTimestampMs_; }
      set {
        battleEndTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "battle_id" field.</summary>
    public const int BattleIdFieldNumber = 4;
    private string battleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BattleId {
      get { return battleId_; }
      set {
        battleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "defender" field.</summary>
    public const int DefenderFieldNumber = 5;
    private global::POGOProtos.Data.Battle.BattleParticipant defender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattleParticipant Defender {
      get { return defender_; }
      set {
        defender_ = value;
      }
    }

    /// <summary>Field number for the "battle_log" field.</summary>
    public const int BattleLogFieldNumber = 6;
    private global::POGOProtos.Data.Battle.BattleLog battleLog_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattleLog BattleLog {
      get { return battleLog_; }
      set {
        battleLog_ = value;
      }
    }

    /// <summary>Field number for the "attacker" field.</summary>
    public const int AttackerFieldNumber = 7;
    private global::POGOProtos.Data.Battle.BattleParticipant attacker_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattleParticipant Attacker {
      get { return attacker_; }
      set {
        attacker_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartGymBattleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartGymBattleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (BattleStartTimestampMs != other.BattleStartTimestampMs) return false;
      if (BattleEndTimestampMs != other.BattleEndTimestampMs) return false;
      if (BattleId != other.BattleId) return false;
      if (!object.Equals(Defender, other.Defender)) return false;
      if (!object.Equals(BattleLog, other.BattleLog)) return false;
      if (!object.Equals(Attacker, other.Attacker)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (BattleStartTimestampMs != 0L) hash ^= BattleStartTimestampMs.GetHashCode();
      if (BattleEndTimestampMs != 0L) hash ^= BattleEndTimestampMs.GetHashCode();
      if (BattleId.Length != 0) hash ^= BattleId.GetHashCode();
      if (defender_ != null) hash ^= Defender.GetHashCode();
      if (battleLog_ != null) hash ^= BattleLog.GetHashCode();
      if (attacker_ != null) hash ^= Attacker.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (BattleStartTimestampMs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BattleStartTimestampMs);
      }
      if (BattleEndTimestampMs != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BattleEndTimestampMs);
      }
      if (BattleId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BattleId);
      }
      if (defender_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Defender);
      }
      if (battleLog_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BattleLog);
      }
      if (attacker_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Attacker);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (BattleStartTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BattleStartTimestampMs);
      }
      if (BattleEndTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BattleEndTimestampMs);
      }
      if (BattleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BattleId);
      }
      if (defender_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Defender);
      }
      if (battleLog_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleLog);
      }
      if (attacker_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Attacker);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartGymBattleResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.BattleStartTimestampMs != 0L) {
        BattleStartTimestampMs = other.BattleStartTimestampMs;
      }
      if (other.BattleEndTimestampMs != 0L) {
        BattleEndTimestampMs = other.BattleEndTimestampMs;
      }
      if (other.BattleId.Length != 0) {
        BattleId = other.BattleId;
      }
      if (other.defender_ != null) {
        if (defender_ == null) {
          defender_ = new global::POGOProtos.Data.Battle.BattleParticipant();
        }
        Defender.MergeFrom(other.Defender);
      }
      if (other.battleLog_ != null) {
        if (battleLog_ == null) {
          battleLog_ = new global::POGOProtos.Data.Battle.BattleLog();
        }
        BattleLog.MergeFrom(other.BattleLog);
      }
      if (other.attacker_ != null) {
        if (attacker_ == null) {
          attacker_ = new global::POGOProtos.Data.Battle.BattleParticipant();
        }
        Attacker.MergeFrom(other.Attacker);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.StartGymBattleResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 16: {
            BattleStartTimestampMs = input.ReadInt64();
            break;
          }
          case 24: {
            BattleEndTimestampMs = input.ReadInt64();
            break;
          }
          case 34: {
            BattleId = input.ReadString();
            break;
          }
          case 42: {
            if (defender_ == null) {
              defender_ = new global::POGOProtos.Data.Battle.BattleParticipant();
            }
            input.ReadMessage(defender_);
            break;
          }
          case 50: {
            if (battleLog_ == null) {
              battleLog_ = new global::POGOProtos.Data.Battle.BattleLog();
            }
            input.ReadMessage(battleLog_);
            break;
          }
          case 58: {
            if (attacker_ == null) {
              attacker_ = new global::POGOProtos.Data.Battle.BattleParticipant();
            }
            input.ReadMessage(attacker_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the StartGymBattleResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_GYM_NOT_FOUND")] ErrorGymNotFound = 2,
        [pbr::OriginalName("ERROR_GYM_NEUTRAL")] ErrorGymNeutral = 3,
        [pbr::OriginalName("ERROR_GYM_WRONG_TEAM")] ErrorGymWrongTeam = 4,
        [pbr::OriginalName("ERROR_GYM_EMPTY")] ErrorGymEmpty = 5,
        [pbr::OriginalName("ERROR_INVALID_DEFENDER")] ErrorInvalidDefender = 6,
        [pbr::OriginalName("ERROR_TRAINING_INVALID_ATTACKER_COUNT")] ErrorTrainingInvalidAttackerCount = 7,
        [pbr::OriginalName("ERROR_ALL_POKEMON_FAINTED")] ErrorAllPokemonFainted = 8,
        [pbr::OriginalName("ERROR_TOO_MANY_BATTLES")] ErrorTooManyBattles = 9,
        [pbr::OriginalName("ERROR_TOO_MANY_PLAYERS")] ErrorTooManyPlayers = 10,
        [pbr::OriginalName("ERROR_GYM_BATTLE_LOCKOUT")] ErrorGymBattleLockout = 11,
        [pbr::OriginalName("ERROR_PLAYER_BELOW_MINIMUM_LEVEL")] ErrorPlayerBelowMinimumLevel = 12,
        [pbr::OriginalName("ERROR_NOT_IN_RANGE")] ErrorNotInRange = 13,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
