// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UseItemEggIncubatorResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from UseItemEggIncubatorResponse.proto</summary>
  public static partial class UseItemEggIncubatorResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for UseItemEggIncubatorResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UseItemEggIncubatorResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFVc2VJdGVtRWdnSW5jdWJhdG9yUmVzcG9uc2UucHJvdG8SH1BPR09Qcm90",
            "b3MuTmV0d29ya2luZy5SZXNwb25zZXMaJ1BPR09Qcm90b3MvSW52ZW50b3J5",
            "L0VnZ0luY3ViYXRvci5wcm90byKfAwobVXNlSXRlbUVnZ0luY3ViYXRvclJl",
            "c3BvbnNlElMKBnJlc3VsdBgBIAEoDjJDLlBPR09Qcm90b3MuTmV0d29ya2lu",
            "Zy5SZXNwb25zZXMuVXNlSXRlbUVnZ0luY3ViYXRvclJlc3BvbnNlLlJlc3Vs",
            "dBI5Cg1lZ2dfaW5jdWJhdG9yGAIgASgLMiIuUE9HT1Byb3Rvcy5JbnZlbnRv",
            "cnkuRWdnSW5jdWJhdG9yIu8BCgZSZXN1bHQSCQoFVU5TRVQQABILCgdTVUND",
            "RVNTEAESHQoZRVJST1JfSU5DVUJBVE9SX05PVF9GT1VORBACEh8KG0VSUk9S",
            "X1BPS0VNT05fRUdHX05PVF9GT1VORBADEhwKGEVSUk9SX1BPS0VNT05fSURf",
            "Tk9UX0VHRxAEEiIKHkVSUk9SX0lOQ1VCQVRPUl9BTFJFQURZX0lOX1VTRRAF",
            "EiQKIEVSUk9SX1BPS0VNT05fQUxSRUFEWV9JTkNVQkFUSU5HEAYSJQohRVJS",
            "T1JfSU5DVUJBVE9SX05PX1VTRVNfUkVNQUlOSU5HEAdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.EggIncubatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse), global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse.Parser, new[]{ "Result", "EggIncubator" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UseItemEggIncubatorResponse : pb::IMessage<UseItemEggIncubatorResponse> {
    private static readonly pb::MessageParser<UseItemEggIncubatorResponse> _parser = new pb::MessageParser<UseItemEggIncubatorResponse>(() => new UseItemEggIncubatorResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UseItemEggIncubatorResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseItemEggIncubatorResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseItemEggIncubatorResponse(UseItemEggIncubatorResponse other) : this() {
      result_ = other.result_;
      EggIncubator = other.eggIncubator_ != null ? other.EggIncubator.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseItemEggIncubatorResponse Clone() {
      return new UseItemEggIncubatorResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "egg_incubator" field.</summary>
    public const int EggIncubatorFieldNumber = 2;
    private global::POGOProtos.Inventory.EggIncubator eggIncubator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.EggIncubator EggIncubator {
      get { return eggIncubator_; }
      set {
        eggIncubator_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UseItemEggIncubatorResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UseItemEggIncubatorResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(EggIncubator, other.EggIncubator)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (eggIncubator_ != null) hash ^= EggIncubator.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (eggIncubator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EggIncubator);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (eggIncubator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EggIncubator);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UseItemEggIncubatorResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.eggIncubator_ != null) {
        if (eggIncubator_ == null) {
          eggIncubator_ = new global::POGOProtos.Inventory.EggIncubator();
        }
        EggIncubator.MergeFrom(other.EggIncubator);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.UseItemEggIncubatorResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (eggIncubator_ == null) {
              eggIncubator_ = new global::POGOProtos.Inventory.EggIncubator();
            }
            input.ReadMessage(eggIncubator_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UseItemEggIncubatorResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_INCUBATOR_NOT_FOUND")] ErrorIncubatorNotFound = 2,
        [pbr::OriginalName("ERROR_POKEMON_EGG_NOT_FOUND")] ErrorPokemonEggNotFound = 3,
        [pbr::OriginalName("ERROR_POKEMON_ID_NOT_EGG")] ErrorPokemonIdNotEgg = 4,
        [pbr::OriginalName("ERROR_INCUBATOR_ALREADY_IN_USE")] ErrorIncubatorAlreadyInUse = 5,
        [pbr::OriginalName("ERROR_POKEMON_ALREADY_INCUBATING")] ErrorPokemonAlreadyIncubating = 6,
        [pbr::OriginalName("ERROR_INCUBATOR_NO_USES_REMAINING")] ErrorIncubatorNoUsesRemaining = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
