// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlatformRequestType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Platform {

  /// <summary>Holder for reflection information generated from PlatformRequestType.proto</summary>
  public static partial class PlatformRequestTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for PlatformRequestType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlatformRequestTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlQbGF0Zm9ybVJlcXVlc3RUeXBlLnByb3RvEh5QT0dPUHJvdG9zLk5ldHdv",
            "cmtpbmcuUGxhdGZvcm0qmgEKE1BsYXRmb3JtUmVxdWVzdFR5cGUSEAoMTUVU",
            "SE9EX1VOU0VUEAASFgoSQlVZX0lURU1fUE9LRUNPSU5TEAISFAoQQlVZX0lU",
            "RU1fQU5EUk9JRBADEhAKDEJVWV9JVEVNX0lPUxAEEhMKD0dFVF9TVE9SRV9J",
            "VEVNUxAFEhwKGFNFTkRfRU5DUllQVEVEX1NJR05BVFVSRRAGYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Networking.Platform.PlatformRequestType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PlatformRequestType {
    [pbr::OriginalName("METHOD_UNSET")] MethodUnset = 0,
    [pbr::OriginalName("BUY_ITEM_POKECOINS")] BuyItemPokecoins = 2,
    [pbr::OriginalName("BUY_ITEM_ANDROID")] BuyItemAndroid = 3,
    [pbr::OriginalName("BUY_ITEM_IOS")] BuyItemIos = 4,
    [pbr::OriginalName("GET_STORE_ITEMS")] GetStoreItems = 5,
    [pbr::OriginalName("SEND_ENCRYPTED_SIGNATURE")] SendEncryptedSignature = 6,
  }

  #endregion

}

#endregion Designer generated code
