// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FortSponsor.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Map.Fort {

  /// <summary>Holder for reflection information generated from FortSponsor.proto</summary>
  public static partial class FortSponsorReflection {

    #region Descriptor
    /// <summary>File descriptor for FortSponsor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortSponsorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGb3J0U3BvbnNvci5wcm90bxITUE9HT1Byb3Rvcy5NYXAuRm9ydCqlAQoL",
            "Rm9ydFNwb25zb3ISEQoNVU5TRVRfU1BPTlNPUhAAEg0KCU1DRE9OQUxEUxAB",
            "EhEKDVBPS0VNT05fU1RPUkUQAhIICgRUT0hPEAMSDAoIU09GVEJBTksQBBIJ",
            "CgVHTE9CRRAFEgsKB1NQQVRVTEEQBhIPCgtUSEVSTU9NRVRFUhAHEgkKBUtO",
            "SUZFEAgSCQoFR1JJTEwQCRIKCgZTTU9LRVIQCmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Map.Fort.FortSponsor), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FortSponsor {
    [pbr::OriginalName("UNSET_SPONSOR")] UnsetSponsor = 0,
    [pbr::OriginalName("MCDONALDS")] Mcdonalds = 1,
    [pbr::OriginalName("POKEMON_STORE")] PokemonStore = 2,
    [pbr::OriginalName("TOHO")] Toho = 3,
    [pbr::OriginalName("SOFTBANK")] Softbank = 4,
    [pbr::OriginalName("GLOBE")] Globe = 5,
    [pbr::OriginalName("SPATULA")] Spatula = 6,
    [pbr::OriginalName("THERMOMETER")] Thermometer = 7,
    [pbr::OriginalName("KNIFE")] Knife = 8,
    [pbr::OriginalName("GRILL")] Grill = 9,
    [pbr::OriginalName("SMOKER")] Smoker = 10,
  }

  #endregion

}

#endregion Designer generated code
